/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Binguni
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblwelcome = new javax.swing.JLabel();
        jlbladmin = new javax.swing.JLabel();
        userpic = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnProjects = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnDonors = new javax.swing.JButton();
        btnDonations = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblwelcome.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jlblwelcome.setForeground(new java.awt.Color(153, 153, 153));
        jlblwelcome.setText(" WELCOME ,");
        jPanel1.add(jlblwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 40));

        jlbladmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbladmin.setForeground(new java.awt.Color(153, 153, 153));
        jlbladmin.setText("Admin");
        jPanel1.add(jlbladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 90, 30));

        userpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_8742495.png"))); // NOI18N
        userpic.setText("jLabel2");
        jPanel1.add(userpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 130, 140));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 102));
        jButton1.setText("Logout ");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, 30));

        btnReports.setBackground(new java.awt.Color(0, 51, 102));
        btnReports.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReports.setForeground(new java.awt.Color(153, 153, 153));
        btnReports.setText("Reports");
        btnReports.setBorder(null);
        jPanel1.add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 240, 40));

        btnProjects.setBackground(new java.awt.Color(0, 51, 102));
        btnProjects.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnProjects.setForeground(new java.awt.Color(153, 153, 153));
        btnProjects.setText("Projects");
        btnProjects.setBorder(null);
        btnProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjectsActionPerformed(evt);
            }
        });
        jPanel1.add(btnProjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 240, 40));

        btnHome.setBackground(new java.awt.Color(0, 51, 102));
        btnHome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(153, 153, 153));
        btnHome.setText("Home");
        btnHome.setBorder(null);
        btnHome.setMaximumSize(new java.awt.Dimension(55, 30));
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 271, 240, 40));

        btnDonors.setBackground(new java.awt.Color(0, 51, 102));
        btnDonors.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDonors.setForeground(new java.awt.Color(153, 153, 153));
        btnDonors.setText("Donors ");
        btnDonors.setBorder(null);
        btnDonors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonorsActionPerformed(evt);
            }
        });
        jPanel1.add(btnDonors, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 240, 40));

        btnDonations.setBackground(new java.awt.Color(0, 51, 102));
        btnDonations.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDonations.setForeground(new java.awt.Color(153, 153, 153));
        btnDonations.setText("Donations");
        btnDonations.setBorder(null);
        btnDonations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonationsActionPerformed(evt);
            }
        });
        jPanel1.add(btnDonations, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 240, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/donation-money-vector-flat-illustration_1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 560, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login login= new login();
        login .setVisible(true);
        this.dispose();
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjectsActionPerformed
        Projectdetails projects= new Projectdetails();
        projects.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProjectsActionPerformed

    private void btnDonorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonorsActionPerformed
       donorRegistration register= new donorRegistration();
        register .setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDonorsActionPerformed

    private void btnDonationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonationsActionPerformed
         DonationProcess donation= new DonationProcess();
        donation.setVisible(true);
        this.dispose();
         
    }//GEN-LAST:event_btnDonationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonations;
    private javax.swing.JButton btnDonors;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnProjects;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlbladmin;
    private javax.swing.JLabel jlblwelcome;
    private javax.swing.JLabel userpic;
    // End of variables declaration//GEN-END:variables
}
